spring:
  application:
    name: my-app
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=projetos;encrypt=false;trustServerCertificate=false;createDatabaseIfNotExist=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 'PutaquePariu24'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      async:
        request-timeout: 5000ms

server:
  port: 8080
  servlet:
    context-path: /api

# Configurações de logging personalizadas
logging:
  level:
    com.example.springcopylot: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    org.springframework.web.servlet.DispatcherServlet: TRACE
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: TRACE
    org.springframework.http.converter: TRACE
    org.apache.catalina.core: DEBUG
    org.apache.coyote.http11: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{requestId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{requestId:-}] %logger{36} - %msg%n"
  file:
    name: logs/application.log    